### ISSUE TITLE
osd vs osd

### ISSUE THREAD

**Issue by danstoner** [autonomy/talos#388]
I recently found the Talos project and was reading thru the website and immediately noticed that you are using "osd" as the name of one of your components.

OSD is a concept / name of something from the Ceph storage project.

I am wondering what happens if someone tries to run Ceph on Talos.

_naming is hard_

**Comment by andrewrynhard** [comment]
Heh. Naming is indeed hard. I actually run Ceph on talos with Rook. `osd` is the "operating system daemon" and there is `osctl` to accompany it. The naming shouldn't cause too much confusion (I hope) since `osd` isn't actually a pod in Kubernetes. It is a container that is run on the host via containerd. Does that help? I can clarify more if you'd like.

**Comment by andrewrynhard** [comment]
@danstoner I hope the naming doesn't cause too much confusion. I'm going to close this out.
